### ISSUE TITLE
Share Name required but not being used by Org when using iDRAC Network Module

### ISSUE THREAD

**Issue by dk-rbrown** [dell/dellemc-openmanage-ansible-modules#403]
Hello. 

I am attempting to configure my org's idrac's through the [iDRAC network module playbook](https://docs.ansible.com/ansible/latest/collections/dellemc/openmanage/idrac_network_module.html). 
The "share name" value is required for this playbook to run. However; our org does not use this with our configurations. 
What null value is acceptable for the playbook to run successfully?
Thank you.

**Comment by MallocArray** [comment]
It is complicated and very confusing to still have that as a required field, but here is a discussion about it:
https://github.com/dell/dellemc-openmanage-ansible-modules/issues/257

Basically, it can be any folder on your Ansible host and it doesn't have to actually be a share, which is why the parameter name is horrible.  The discussion link has an option, but for my tasks, I just use:
```
share_name: /tmp
```
and this works without error and without actually sharing my /tmp folder.

**Comment by dbond007** [comment]
Thanks for this, I have been looking into using these modules and reading through the documentation shows that its a required value, but I could not understand what it was used for and what it should be set to, I have been wondering why do I need to provide a share when setting an IP, whats in that share.
The documentation, well the module really, needs updating and these things removed if they are no longer needed.

**Comment by anupamaloke** [comment]
@dk-rbrown, thank you for the feedback. It is one of the top priority items on the roadmap and we will be doing this in phases over the next few months.
