### ISSUE TITLE
SysProfile with setting PerfOptimized - no changes

### ISSUE THREAD

**Issue by GamerGun** [dell/dellemc-openmanage-ansible-modules#491]
### How can the team help?

**Details: ?**

As with https://github.com/dell/dellemc-openmanage-ansible-modules/issues/415

I can't get SysProfile with setting PerfOptimized to work;

Item setting: SysProfile
Item value: PerfOptimized
Message: No changes found to commit!

        attributes:
          SysProfile: "PerfOptimized"

Redfish API still shows PerfPerWattOptimizedDapc 

Happens on R740 system

**Comment by anupamaloke** [comment]
@GamerGun, thank you for submitting this issue. 
System Profile settings have a dependency on other BIOS attributes as well. If you set the `SysProfile` attribute to `PerfOptimized` then you might need to also change other BIOS attributes else it might not get applied. For e.g. when I use the GUI to change the 'SysProfile' to `PerfOptimized`, iDRAC automatically sets the CPU Power Management (i.e. `ProcPwrPerf`) to `OsDbpm`.  See below screenshot:

![image](https://user-images.githubusercontent.com/9712307/231459699-178dc830-577c-450b-b319-05397416d810.png)

Also, following is the text from the [BIOS Attribute Registry](https://www.dell.com/support/manuals/en-us/idrac9-lifecycle-controller-v5.x-series/idrac9_racadm_ar_refguide/bios.sysprofilesettings.sysprofile-read-or-write?guid=guid-3acb9873-9c08-4b2d-9fac-01cbf158b0d8&lang=en-us) for "System Profile":

> Performance-per-watt (OS), otherwise known as 'OS Control', is similar to the DAPC profile for all sub-options except for the CPU Power Management. The power management scheme used for this profile is called 'OS DBPM', which allows the Operating System to manipulate processor frequencies for higher power efficiency.

But it seems that you can only set the `ProcPowerPerf` attribute when the `SysProfile` attribute is set to `Custom`. See below is the excerpt from [BIOS attribute registry](https://www.dell.com/support/manuals/en-us/idrac9-lifecycle-controller-v5.x-series/idrac9_racadm_ar_refguide/bios.sysprofilesettings.procpwrperf-read-or-write?guid=guid-00db5269-0483-42b8-acad-d11359b595fc&lang=en-us):

> Has a dependency on the System Profile. Can only be set if the System Profile is set to Custom.

So, IMHO, the issue that you are observing could be due to the BIOS attributes dependency. You might have to execute the following workflow to set the system profile using the `idrac_bios` module:
- Set the `SysProfile` to `Custom`. Reboot server to apply changes.
- Next, set the `ProfPowerPerf` to `OsDbpm` and `SysProfile` to `PerfOptimized`. Reboot server to apply changes.

If you want to minimize the number of reboots, then you can import a small SCP with only these BIOS attributes.

**Comment by anupamaloke** [comment]
@GamerGun, I am marking this issue as closed. Please reopen or raise a new issue if you face any issue while using OpenManage Ansible modules.
