### ISSUE TITLE
[BUG]: ome_device_quick_deploy will not deploy a new config to a slot with IPv6 disabled

### ISSUE THREAD

**Issue by jason-technology** [dell/dellemc-openmanage-ansible-modules#533]
### Bug Description

If there is already a configuration on a Quick Deploy slot, ipv6_enabled: False will apply properly.
If this is a new slot and the first configuration run, ipv6_enabled: False will result in an error about ipv6_prefix_length being incorrect.  This happens regardless of the IPv6 prefix setting.
Running once with enabled, then a second time with disabled works.

### Component or Module Name

ome_device_quick_deploy

### Ansible Version

2.15.2

### Python Version

3.10.12

### iDRAC/OME/OME-M version

OME-M 2.10.10

### Operating System

Ubuntu 22.04.3 LTS

### Playbook Used

- hosts: MX7000ChassisSlots
  connection: local
  gather_facts: false
  name: Chassis Server Slot Operations

  tasks:
    - name: Configure Slot Quick Deploy settings
      dellemc.openmanage.ome_device_quick_deploy:
        hostname: "{{ hostvars['OMEModular']['ome_ip'] }}"
        username: "{{ hostvars['OMEModular']['ome_login'] }}"
        password: "{{ hostvars['OMEModular']['ome_password'] }}"
        validate_certs: false
        device_service_tag: "{{ parent_chassis }}"
        setting_type: ServerQuickDeploy
        quick_deploy_options:
          # password: "{{ quick_password }}"
          ipv4_enabled: true
          ipv4_network_type: Static
          ipv4_subnet_mask: "{{ quick_netmask }}"
          ipv4_gateway: "{{ quick_gateway }}"
          ipv6_enabled: false
          ipv6_network_type: Static
          ipv6_prefix_length: 64
          ipv6_gateway: "::"
          slots:
            - slot_id: "{{ slot_id }}"
              slot_ipv4_address: "{{ quick_ip }}"
              slot_ipv6_address: "::"
      register: quick_slot_output
      tags:
        - quick_slot_setup

    - name: Debug Slot Quick Deploy
      ansible.builtin.debug:
        var: quick_slot_output
      tags:
        - quick_slot_setup_debug

### Logs

.

### Steps to Reproduce

Run playbook against new chassis using ipv6_enabled: False

### Expected Behavior

Slot configured

### Actual Behavior

Ansible Errors with "Unable to complete"
OME-M errors with incorrect ipv6 prefix setting

**Comment by sachin-apa** [comment]
@jason-technologywhen i try to reproduce this defect i always end up with #532 , Can you please help me out on steps to reproduce, May be elaborate/update the issue with more details. I understand it should be ran on new chassis, is there any alternatives to reproduce this?

**Comment by sachin-apa** [comment]
In our code we are checking if ipv6 input, if false we were just sending back whatever the API GET returns to us.. and the API GET is returning the default prefix length as 0 and hence you are seeing the job failure calling out that prefix length is invalid.

The suggested workaround is good, when it comes as default value from the argument specs instead of hard coding which can be misleading to users who don't send those values from a playbook.

The main issue is that when we send ipv6 as disable/false and prefix length as 0(invalid) the OME-M job should ideally be ignoring the ipv6 settings as we have disabled it . But it is failing with a prefix length error which we have reported to OME-M team internally and they are gonna fix it (ETA yet to get updates).
